# Generated by Django 4.1.7 on 2023-03-15 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0006_workout_total_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='muscle_group',
            field=models.ForeignKey(default='Upper Body', on_delete=django.db.models.deletion.CASCADE, to='workouts.muscle_groups'),
        ),
        migrations.AlterField(
            model_name='movements',
            name='name',
            field=models.CharField(default='Bench Press', max_length=100),
        ),
        migrations.AlterField(
            model_name='muscle_groups',
            name='name',
            field=models.CharField(default='Upper Body', max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='movement',
            field=models.ForeignKey(default='Bench Press', on_delete=django.db.models.deletion.CASCADE, to='workouts.movements'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='muscle_group',
            field=models.ForeignKey(default='Upper Body', on_delete=django.db.models.deletion.CASCADE, to='workouts.muscle_groups'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='reps',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='workout',
            name='sets',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(default='Kyle', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workout',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
