# Generated by Django 4.1.7 on 2023-03-15 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0008_alter_movements_muscle_group_alter_movements_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='muscle_groups',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='movement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.movements'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='muscle_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.muscle_groups'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='reps',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workout',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
